// Shared visual shell for the gamebook - the one place that defines what a
// "dossier" page looks like, so no chapter re-implements its own
// header/redaction/QR styling.
//
// Fonts are deliberately Typst's own bundled OFL fonts (Libertinus Serif,
// DejaVu Sans Mono), not Windows-supplied fonts like Times New Roman or
// Courier New: KDP requires every font to be fully embeddable, and
// commercial Windows fonts commonly restrict embedding.
//
// Interior is black & white ink, but KDP's B&W printing still halftones
// grayscale/solid fills correctly (like any B&W book with photos or
// shaded boxes) - it only means no color ink, not "no gray or black
// fills". The reversed (white-on-black) panels below lean on that.

#import "kdp.typ": kdp-page, page-width, page-height

// Reads the app's real dilemma content instead of retyping it - the book
// and the app must never drift out of sync on dilemma text. Compile with
// `--root <repo root>` so this root-relative path resolves.
#let dilemmas-en = json("/backend/data/dilemmas_en.json")

#let find-dilemma(id) = {
  let matches = dilemmas-en.filter(d => d._id == id)
  assert(
    matches.len() == 1,
    message: "dilemma id not found in backend/data/dilemmas_en.json: " + id,
  )
  matches.first()
}

// The chapter registry: single source of truth for chapter -> title/theme
// intro/stamp/QR slugs/dilemma ids. Shared, in spirit, with TASK-291's
// eventual backend mapping - both should read the same shape one day.
#let chapters-registry = json("/book/chapters/registry.json")

// A "redacted" black bar, standing in for censored text in the dossier art
// direction.
#let redacted(width: 4em) = box(width: width, height: 0.85em, fill: black)

// A small rotated bordered "ink stamp" accent, e.g. #stamp("Open").
#let stamp(label, angle: -7deg) = rotate(angle, box(
  stroke: 1pt,
  inset: (x: 0.6em, y: 0.35em),
)[
  #text(font: "DejaVu Sans Mono", size: 8pt, weight: "bold", tracking: 1.5pt, upper(label))
])

// An enlarged, bolded first letter - a lightweight "raised initial"
// rather than a true multi-line wrap-around drop cap (Typst has no
// built-in primitive for the latter, and hand-rolling one reliably was
// judged not worth the fragility for a two-line intro paragraph).
#let lede(s) = {
  text(size: 2.3em, weight: "bold")[#s.slice(0, 1)]
  text(s.slice(1))
}

// One QR "evidence tag": bordered card with a tag id, the QR, a mode
// label, and its caption. qr-slug names the PNG generated by
// book/qr/generate_qr.py (book/qr/<qr-slug>.png). The PNG is a
// placeholder pointing at a URL the backend doesn't resolve to a fixed
// dilemma set yet - see TASK-291.
#let evidence-tag(qr-slug: "", tag: "", label: "", caption: "") = block(
  width: 100%,
  stroke: 0.6pt,
  inset: 0.9em,
)[
  #align(center)[
    #text(font: "DejaVu Sans Mono", size: 7pt, tracking: 1.5pt, fill: luma(40%))[#tag]
    #v(0.5em)
    #image("/book/qr/" + qr-slug + ".png", width: 1.05in)
    #v(0.4em)
    #text(font: "DejaVu Sans Mono", size: 9pt, weight: "bold", tracking: 1pt, upper(label))
    #v(0.25em)
    #text(size: 8pt, style: "italic", caption)
  ]
]

// The two-QR chapter opener: same 5 dilemmas either way, only the code
// scanned changes whether they're played alone or with a table of people.
#let mode-select(solo-slug: "", party-slug: "") = grid(
  columns: (1fr, 1fr),
  column-gutter: 1.2em,
  evidence-tag(
    qr-slug: solo-slug,
    tag: "PROCEDURE A",
    label: "Solo Verdict",
    caption: [Open this case alone. Read, decide, scan when you're done.],
  ),
  evidence-tag(
    qr-slug: party-slug,
    tag: "PROCEDURE B",
    label: "Convene Tribunal",
    caption: [Gather the table. Everyone scans this on their own phone before anyone reads aloud.],
  ),
)

// A reversed tag marking one Exhibit.
#let exhibit-tag(n) = box(fill: black, inset: (x: 0.5em, y: 0.3em))[
  #text(font: "DejaVu Sans Mono", size: 8pt, weight: "bold", fill: white, tracking: 1pt)[EXHIBIT #n]
]

// A bordered placeholder standing in for a photograph, since no artwork
// exists yet - corner brackets like a viewfinder, framed as evidence not
// yet entered into the record rather than looking like a broken image.
#let image-placeholder(height: 2.5in) = box(width: 100%, height: height, stroke: 0.8pt)[
  #place(center + horizon, text(
    font: "DejaVu Sans Mono", size: 8pt, tracking: 2pt, fill: luma(55%),
  )[PHOTOGRAPHIC EVIDENCE --- PENDING])
  #let corner(x, y) = place(
    if y == top { top } else { bottom } + if x == left { left } else { right },
    box(width: 0.3in, height: 0.3in, stroke: (
      top: if y == top { 1pt } else { 0pt },
      bottom: if y == bottom { 1pt } else { 0pt },
      left: if x == left { 1pt } else { 0pt },
      right: if x == right { 1pt } else { 0pt },
    )),
  )
  #corner(left, top)
  #corner(right, top)
  #corner(left, bottom)
  #corner(right, bottom)
]

// One answer, styled after the webapp's actual `.btn-yes`/`.btn-no`
// buttons (frontend/src/styles/shared.css): flex: 1 (equal width),
// border-radius: 0 (sharp corners, not rounded), a 2px border, side by
// side with a small gap - reproduced here as a two-column grid of
// square-cornered bordered boxes rather than the app's color-coded fill,
// since this interior is black & white ink. Each answer is a
// `grid.cell(stroke: ...)` rather than a `box` with `height: 100%`: a
// percentage height inside a `box` resolves against the *page's*
// available height in an auto-sized flow position, not the grid row
// (confirmed the hard way - it inflated the book from 16 to 26 pages).
// `grid.cell` draws its stroke against the cell's actual allocated area,
// which the grid already sizes to the row's tallest content, so both
// answers end up the same height without that trap.
//
// The answer text itself uses Shadows Into Light (`book/fonts/`, OFL -
// same embeddable-font requirement as every other font in this book),
// a genuine pencil/handwriting-style face, standing in for the reader
// marking their own choice by hand; the A/B tag stays in the systematic
// mono face so it's still a quick reference at the table.
#let answer-button-content(tag, label) = [
  #text(font: "DejaVu Sans Mono", size: 7pt, tracking: 1.5pt, fill: luma(40%))[#tag]
  #v(0.4em)
  #align(center, text(font: "Shadows Into", size: 15pt, label))
]

#let answer-buttons(first, second) = grid(
  columns: (1fr, 1fr),
  column-gutter: 10pt,
  grid.cell(stroke: 2pt, inset: 0.9em, answer-button-content("A", first)),
  grid.cell(stroke: 2pt, inset: 0.9em, answer-button-content("B", second)),
)

// One dilemma, one page: an Exhibit tag + title, an image placeholder,
// the dilemma text, and the two answers as webapp-style rectangular
// buttons. Called once per entry in a chapter's `dilemmas` registry list.
#let exhibit-page(n, title, dilemma) = {
  exhibit-tag(n)
  h(0.6em)
  text(size: 15pt, weight: "bold", title)
  v(0.9em)
  image-placeholder()
  v(0.9em)
  dilemma.dilemma
  v(1em)
  answer-buttons(dilemma.firstAnswer, dilemma.secondAnswer)
}

// Full-bleed header band - drawn as a page *background*, which Typst lays
// out against the full physical page regardless of body margins (verified
// empirically: a background rect reaches every physical page edge). This
// only needs to be symmetric/full-width to be safe on both recto and
// verso pages under this book's mirrored (`binding: left`) margins - an
// asymmetric bleed element (touching only one side) would additionally
// need to know which physical side is "outside" per page, which this
// deliberately avoids needing.
#let bleed-band-height = 1.7in

#let bleed-band(kicker: none, title: "") = place(
  top + left,
  block(
    width: page-width,
    height: bleed-band-height,
    fill: black,
    inset: (left: 0.7in, right: 0.7in, top: 0.55in),
  )[
    #set text(fill: white)
    #if kicker != none {
      text(font: "DejaVu Sans Mono", size: 8pt, tracking: 2pt, upper(kicker))
      v(0.5em)
    }
    #text(size: 20pt, weight: "bold", tracking: 1pt, upper(title))
  ],
)

// Standard footer: a centered page number, plus a running chapter title
// when inside one (`label:`) so a reader flipping the book can tell which
// Case File a page belongs to without hunting back for its opener. Front
// matter/back matter pages call it with no label - just the number.
// Suppressed entirely on the title page (its background is full-bleed
// black, and a default dark footer would be invisible against it).
#let page-footer(label: none) = context [
  #align(center)[
    #if label != none {
      text(font: "DejaVu Sans Mono", size: 7pt, fill: luma(55%), tracking: 1pt)[#upper(label)]
      h(0.6em)
      text(font: "DejaVu Sans Mono", size: 7pt, fill: luma(45%))[--- #counter(page).display() ---]
    } else {
      text(font: "DejaVu Sans Mono", size: 8pt, fill: luma(45%))[#counter(page).display()]
    }
  ]
]

// A page that is entirely black, edge to edge (true full-page bleed, not
// just a top band) - for the title page. Uses the same page(background:)
// mechanism as bleed-band, sized to the whole physical page instead of a
// header-height strip.
#let full-bleed-page(page-count: 24, body) = kdp-page(page-count: page-count, {
  set page(
    footer: none,
    background: place(top + left, block(width: page-width, height: page-height, fill: black)),
  )
  set text(font: "Libertinus Serif", size: 10.5pt, fill: white)
  body
})

// A front-matter page (instructions, title page, closing page, ...): same
// KDP geometry and fonts as a chapter. Pass `band: (kicker: ..., title:
// ...)` to get the same full-bleed header chapters use (and the matching
// reserved space so body content clears it); leave it `none` for a plain
// page (e.g. the full-bleed-black title page draws its own background).
#let front-matter-page(page-count: 24, show-footer: true, band: none, body) = {
  kdp-page(page-count: page-count, extra-top: if band != none { bleed-band-height } else { 0pt }, {
    set page(
      footer: if show-footer { page-footer() } else { none },
      background: if band != none { bleed-band(kicker: band.at("kicker", default: none), title: band.title) },
    )
    set text(font: "Libertinus Serif", size: 10.5pt)
    set par(justify: true, leading: 0.75em)
    body
  })
}

// One printed chapter: a themed cluster of 5 dilemmas, opened by the
// solo/party QR pair. Reads its content from `chapters-registry[key]`
// (title, theme intro, stamp, QR slugs, dilemma ids) rather than taking
// each field as a separate argument, so a chapter file reduces to
// `#chapter-page(key: "c1") <chapter-c1>` and the registry stays the one
// place that can drift out of sync with the printed book.
#let chapter-page(key: "", page-count: 24) = {
  let c = chapters-registry.at(key)
  kdp-page(page-count: page-count, extra-top: bleed-band-height, {
    set page(
      footer: page-footer(label: c.title),
      background: bleed-band(kicker: "Case File No. " + str(c.number), title: c.title),
    )
    set text(font: "Libertinus Serif", size: 10.5pt)
    set par(justify: true, leading: 0.75em)

    stamp(c.stamp)
    v(0.6em)
    emph(lede(c.themeIntro))
    v(1.2em)

    mode-select(solo-slug: c.soloSlug, party-slug: c.partySlug)

    // One dilemma per page (AC: image placeholder + webapp-style answer
    // buttons need the room) - pagebreak before each entry, including the
    // first, separates every Exhibit from the opener and from each other.
    for (i, entry) in c.dilemmas.enumerate() {
      pagebreak()
      exhibit-page(str(i + 1), entry.title, find-dilemma(entry.id))
    }
  })
}
