// Shared visual shell for the gamebook - the one place that defines what a
// "dossier" page looks like, so no chapter re-implements its own
// header/redaction/QR styling.
//
// Fonts are deliberately Typst's own bundled OFL fonts (Libertinus Serif,
// DejaVu Sans Mono), not Windows-supplied fonts like Times New Roman or
// Courier New: KDP requires every font to be fully embeddable, and
// commercial Windows fonts commonly restrict embedding.
//
// Interior is black & white ink, but KDP's B&W printing still halftones
// grayscale/solid fills correctly (like any B&W book with photos or
// shaded boxes) - it only means no color ink, not "no gray or black
// fills". The reversed (white-on-black) panels below lean on that.
//
// Deliberately NOT attempted here: true edge-to-edge bleed art (e.g. a
// header band running into the physical page edge). Doing that correctly
// needs the render to know, per page, which side is the gutter under
// this book's mirrored `binding: left` margins (recto vs verso resolve
// inside/outside to opposite physical sides) - getting that wrong would
// misalign art against the trim on a real print run. Every reversed panel
// below is full CONTENT width (between the margins), not full bleed - a
// safer, still-strong option; true bleed art is a later, verified pass.

#import "kdp.typ": kdp-page

// Reads the app's real dilemma content instead of retyping it - the book
// and the app must never drift out of sync on dilemma text. Compile with
// `--root <repo root>` so this root-relative path resolves.
#let dilemmas-en = json("/backend/data/dilemmas_en.json")

#let find-dilemma(id) = {
  let matches = dilemmas-en.filter(d => d._id == id)
  assert(
    matches.len() == 1,
    message: "dilemma id not found in backend/data/dilemmas_en.json: " + id,
  )
  matches.first()
}

// A "redacted" black bar, standing in for censored text in the dossier art
// direction.
#let redacted(width: 4em) = box(width: width, height: 0.85em, fill: black)

// A reversed (white-on-black), full-content-width header panel - the
// dossier's "cover sheet" motif. Used for the running case header and,
// larger, for the title page.
#let case-band(kicker: none, title: "", size: 20pt) = block(
  width: 100%,
  fill: black,
  inset: (x: 1.1em, y: 1em),
)[
  #set text(fill: white)
  #if kicker != none {
    text(font: "DejaVu Sans Mono", size: 8pt, tracking: 2pt, upper(kicker))
    v(0.5em)
  }
  #text(size: size, weight: "bold", tracking: 1pt, upper(title))
]

// A small rotated bordered "ink stamp" accent, e.g. #stamp("Open").
#let stamp(label, angle: -7deg) = rotate(angle, box(
  stroke: 1pt,
  inset: (x: 0.6em, y: 0.35em),
)[
  #text(font: "DejaVu Sans Mono", size: 8pt, weight: "bold", tracking: 1.5pt, upper(label))
])

// One QR "evidence tag": bordered card with a tag id, the QR, a mode
// label, and its caption. qr-slug names the PNG generated by
// book/qr/generate_qr.py (book/qr/<qr-slug>.png). The PNG is a
// placeholder pointing at a URL the backend doesn't resolve to a fixed
// dilemma set yet - see TASK-291.
#let evidence-tag(qr-slug: "", tag: "", label: "", caption: "") = block(
  width: 100%,
  stroke: 0.6pt,
  inset: 0.9em,
)[
  #align(center)[
    #text(font: "DejaVu Sans Mono", size: 7pt, tracking: 1.5pt, fill: luma(40%))[#tag]
    #v(0.5em)
    #image("/book/qr/" + qr-slug + ".png", width: 1.05in)
    #v(0.4em)
    #text(font: "DejaVu Sans Mono", size: 9pt, weight: "bold", tracking: 1pt, upper(label))
    #v(0.25em)
    #text(size: 8pt, style: "italic", caption)
  ]
]

// The two-QR chapter opener: same 5 dilemmas either way, only the code
// scanned changes whether they're played alone or with a table of people.
#let mode-select(solo-slug: "", party-slug: "") = grid(
  columns: (1fr, 1fr),
  column-gutter: 1.2em,
  evidence-tag(
    qr-slug: solo-slug,
    tag: "PROCEDURE A",
    label: "Solo Verdict",
    caption: [Open this case alone. Read, decide, scan when you're done.],
  ),
  evidence-tag(
    qr-slug: party-slug,
    tag: "PROCEDURE B",
    label: "Convene Tribunal",
    caption: [Gather the table. Everyone scans this on their own phone before anyone reads aloud.],
  ),
)

// A reversed tag marking one Exhibit, plus a left rule running the height
// of that exhibit's block - a "flagged in the folder" margin cue.
#let exhibit(n, body) = block(
  stroke: (left: 1.2pt + black),
  inset: (left: 1em, rest: 0pt),
  above: 1.1em,
  below: 0pt,
)[
  #box(fill: black, inset: (x: 0.5em, y: 0.3em))[
    #text(font: "DejaVu Sans Mono", size: 8pt, weight: "bold", fill: white, tracking: 1pt)[EXHIBIT #n]
  ]
  #v(0.5em)
  #body
]

// A front-matter page (instructions, title page, ...): same KDP geometry
// and fonts as a chapter, but the caller controls its own chrome.
#let front-matter-page(page-count: 24, body) = {
  kdp-page(page-count: page-count, {
    set text(font: "Libertinus Serif", size: 10.5pt)
    set par(justify: true, leading: 0.75em)
    body
  })
}

// One printed chapter: a themed cluster of 5 dilemmas, opened by the
// solo/party QR pair. `dilemma-ids` pulls real dilemmas straight from
// dilemmas_en.json - never retyped text.
#let chapter-page(
  number: 1,
  title: "",
  theme-intro: none,
  solo-slug: "",
  party-slug: "",
  page-count: 24,
  dilemma-ids: (),
) = {
  kdp-page(page-count: page-count, {
    set text(font: "Libertinus Serif", size: 10.5pt)
    set par(justify: true, leading: 0.75em)

    case-band(kicker: "Case File No. " + str(number), title: title)
    v(1em)

    if theme-intro != none {
      grid(
        columns: (auto, 1fr),
        column-gutter: 1em,
        align(top, stamp("Open")),
        align(horizon, emph(theme-intro)),
      )
      v(1.2em)
    }

    mode-select(solo-slug: solo-slug, party-slug: party-slug)
    v(1.3em)

    for (i, id) in dilemma-ids.enumerate() {
      let d = find-dilemma(id)
      exhibit(str(i + 1), [
        #d.dilemma
        #v(0.6em)
        #list(
          [*A.* #d.firstAnswer],
          [*B.* #d.secondAnswer],
        )
      ])
    }
  })
}
