// Shared visual shell for every Case File - the one place that defines
// what a "dossier" page looks like, so no case file re-implements its own
// header/redaction/QR placement (repo convention: shared pattern instead
// of copy-pasted styling per page).
//
// Fonts are deliberately Typst's own bundled OFL fonts (Libertinus Serif,
// DejaVu Sans Mono), not Windows-supplied fonts like Times New Roman or
// Courier New: KDP requires every font to be fully embeddable, and
// commercial Windows fonts commonly restrict embedding. Swap for a
// licensed display/stamp font later if the final art direction needs one,
// but keep it OFL/embeddable.

#import "kdp.typ": kdp-page

// Reads the app's real dilemma content instead of retyping it - the book
// and the app must never drift out of sync on dilemma text. Compile with
// `--root <repo root>` so this root-relative path resolves.
#let dilemmas-en = json("/backend/data/dilemmas_en.json")

#let find-dilemma(id) = {
  let matches = dilemmas-en.filter(d => d._id == id)
  assert(
    matches.len() == 1,
    message: "dilemma id not found in backend/data/dilemmas_en.json: " + id,
  )
  matches.first()
}

// A "redacted" black bar, standing in for censored text in the dossier art
// direction.
#let redacted(width: 4em) = box(width: width, height: 0.85em, fill: black)

#let classified-header(case-id) = {
  set text(font: "DejaVu Sans Mono", size: 8pt, tracking: 2pt)
  align(center, upper[CLASSIFIED -- CASE #case-id])
}

// One printed Case File. `dilemma-ids` pulls real dilemmas straight from
// dilemmas_en.json; `qr-slug` names the PNG generated by
// book/qr/generate_qr.py (book/qr/<qr-slug>.png).
#let case-page(
  case-id: "",
  title: "",
  qr-slug: "",
  page-count: 24,
  intro: none,
  dilemma-ids: (),
) = {
  kdp-page(page-count: page-count, {
    set text(font: "Libertinus Serif", size: 10.5pt)
    set par(justify: true, leading: 0.75em)

    classified-header(case-id)
    v(0.6em)
    line(length: 100%, stroke: 0.4pt)
    v(0.8em)
    align(center, text(size: 20pt, weight: "bold", tracking: 1pt, upper(title)))
    v(1.2em)

    if intro != none {
      emph(intro)
      v(1em)
    }

    for id in dilemma-ids {
      let d = find-dilemma(id)
      v(0.8em)
      d.dilemma
      v(0.8em)
      list(
        [*A.* #d.firstAnswer],
        [*B.* #d.secondAnswer],
      )
      v(0.8em)
      line(length: 40%, stroke: 0.3pt)
    }

    v(1fr)
    align(center)[
      #line(length: 60%, stroke: 0.3pt)
      #v(0.5em)
      #text(size: 8pt, style: "italic")[Scan to log your verdict and unlock the archetype]
      #v(0.4em)
      #image("/book/qr/" + qr-slug + ".png", width: 1.1in)
    ]
  })
}
