import { useTranslation } from 'react-i18next';

const pages = {
  en: { privacy: ['Privacy notice', 'Controller: Tommaso Bersani — tommasobersani@gmail.com.', 'We process the data necessary to provide and secure the game, including anonymous session identifiers, device language and timezone, and game requests. Google Analytics is optional, starts only after consent, receives no email, answer text, token or custom user ID, and is used only for aggregate web analytics. No advertising or profiling is used. Google Analytics event and user data retention is two months. You can withdraw consent at any time from Privacy preferences.'], cookies: ['Cookie policy', 'The site uses necessary first-party browser storage for the anonymous game, session, language and technical preferences. The mtm_web_analytics_consent cookie stores your Analytics choice for 180 days. If accepted, Google Analytics may create first-party _ga cookies for aggregate measurement. Revocation removes known _ga cookies and reloads without the Google tag.'] },
  it: { privacy: ['Informativa privacy', 'Titolare: Tommaso Bersani — tommasobersani@gmail.com.', 'Trattiamo i dati necessari a fornire e proteggere il gioco, inclusi identificativi anonimi di sessione, lingua e fuso orario del dispositivo e richieste di gioco. Google Analytics è facoltativo, parte solo dopo il consenso, non riceve email, testo delle risposte, token o user ID personalizzati ed è usato solo per analytics web aggregato. Non usiamo advertising o profilazione. La conservazione dei dati evento e utente Google Analytics è di due mesi. Puoi revocare il consenso in ogni momento da Preferenze privacy.'], cookies: ['Cookie policy', 'Il sito usa storage first-party necessario per gioco anonimo, sessione, lingua e preferenze tecniche. Il cookie mtm_web_analytics_consent conserva la scelta Analytics per 180 giorni. Se accetti, Google Analytics può creare cookie first-party _ga per misurazione aggregata. La revoca elimina i cookie _ga conosciuti e ricarica senza il tag Google.'] },
};

export default function LegalScreen({ type }) {
  const { i18n } = useTranslation(); const locale = i18n.resolvedLanguage === 'it' ? 'it' : 'en'; const [title, contact, body] = pages[locale][type];
  return <main className="legal-screen"><article><h1>{title}</h1><p>{contact}</p><p>{body}</p><a href="/">← Home</a></article></main>;
}
